### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by kavikomi** [newfies-dialer/newfies-dialer-enterprise#1]
hello

I install newsfied dialer on server debian 8 and after installation I have this message

502 Bad Gateway

I user your guide?

https://newfies-dialer.readthedocs.io/en/latest/beginner-guide.html#set-hostname

why it not work in first time?

tanks to reply solution

**Comment by areski** [comment]
We discontinued the opensource version of Newfies-Dialer 2 years ago, checkout our website if you need to purchase a current version: https://www.newfies-dialer.org/
